version: '3.7'

networks:
  my_network:

services:

  db-develop:
    container_name: db-develop
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:5434:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      TZ: "Europe/Moscow"
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  redis:
    image: redis:7.2.1-alpine
    volumes:
      - redis-data:/data
    ports:
      - "7379:6379"
    command:
      - redis-server
    networks:
      - my_network
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - my_network

volumes:
  db:
  redis-data:
  redis-insight:
